import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Navigation from "@/components/navigation/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="fixed w-full flex justify-center z-20">
          <Image priority width={375} height={44} src="/Status-Bar.png" alt="phone status bar" />
        </div>
        {children}
        <Navigation />
      </body>
    </html>
  );
}